apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gm9w044ee-nodejs-gitops
  description: This is GitOps manifest for gm9w044ee-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gm9w044ee-nodejs
    backstage.io/kubernetes-id: gm9w044ee-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gm9w044ee-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gm9w044ee-nodejs
