apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gm9w044ee-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gm9w044ee-nodejs 
  name: gm9w044ee-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gm9w044ee-nodejs 
